# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  database: vr_store_dev
  username: vr_user
  password: vruser123
  pool: 5
test:
  adapter: mysql2
  database: vr_store_test 
  username: vr_user
  password: vruser123
  pool: 5

production:
  adapter: mysql2
  database: vr_store_prod
  username: vr_user
  password: vruser123
  pool: 5
